interview:
  target: task-one
  outputs:
    task-one:
      dataset: interview
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: mag-interactive
      threads: 1
      type: bigquery
